# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-21 10:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uberdriver', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_location', to='uberdriver.Location')),
                ('passenger_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uberdriver.Destination')),
                ('pickupoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uberdriver.Location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
