# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-21 10:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand', models.CharField(max_length=50)),
                ('numberplate', models.CharField(max_length=50, unique=True)),
                ('seats', models.IntegerField()),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('serial_number', models.AutoField(primary_key=True, serialize=False)),
                ('destination', models.CharField(max_length=50)),
                ('leaving_time', models.DateTimeField()),
                ('bookers', models.ManyToManyField(blank=True, related_name='passgers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Driver_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('phonenumber', models.IntegerField(null=True)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('car', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='uberdriver.Car')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Longitude', models.IntegerField()),
                ('latitude', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='destination',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uberdriver.Driver_profile'),
        ),
    ]
