# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-21 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uberdriver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver_profile',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
