# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-21 10:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uberdriver', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='driver',
        ),
        migrations.AddField(
            model_name='driver_profile',
            name='destinations',
            field=models.ManyToManyField(to='uberdriver.Destination'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='bookers',
            field=models.ManyToManyField(blank=True, related_name='passengers', to=settings.AUTH_USER_MODEL),
        ),
    ]
