# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-21 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uberdriver', '0002_driver_profile_email_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver_profile',
            name='phonenumber',
            field=models.IntegerField(null=True),
        ),
    ]
