# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-21 11:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uberdriver', '0002_auto_20180521_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver_profile',
            name='destinations',
        ),
        migrations.AddField(
            model_name='destination',
            name='driver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='uberdriver.Driver_profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='destination',
            name='bookers',
            field=models.ManyToManyField(blank=True, related_name='passgers', to=settings.AUTH_USER_MODEL),
        ),
    ]
