# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-19 09:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uberdriver', '0002_driver_profile_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver_profile',
            name='car',
        ),
        migrations.RemoveField(
            model_name='driver_profile',
            name='pickup',
        ),
        migrations.AddField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='uberdriver.Driver_profile'),
            preserve_default=False,
        ),
    ]
