# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-19 10:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uberdriver', '0003_auto_20180519_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver_profile',
            name='driver_destination',
        ),
    ]
