# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-19 10:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uberdriver', '0004_remove_driver_profile_driver_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver_profile',
            name='driver_destination',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='uberdriver.Destination'),
            preserve_default=False,
        ),
    ]
