# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-19 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uberdriver', '0007_auto_20180519_1407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='name',
            new_name='destination',
        ),
        migrations.RemoveField(
            model_name='driver_profile',
            name='driver_destination',
        ),
        migrations.AddField(
            model_name='destination',
            name='driver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='uberdriver.Driver_profile'),
            preserve_default=False,
        ),
    ]
