# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-19 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uberdriver', '0008_auto_20180519_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='leaving_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
