# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-19 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uberdriver', '0009_destination_leaving_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='leaving_time',
            field=models.DateTimeField(null=True),
        ),
    ]
